var mainFixture = physics_fixture_create();
physics_fixture_set_box_shape(mainFixture, 128, 32);
var wheelFixture = physics_fixture_create();
physics_fixture_set_circle_shape(wheelFixture, 32);
var o_id1 = instance_create_layer(x, y + 55, "Instances", oWheel);
physics_fixture_bind(mainFixture, id);
physics_fixture_bind(wheelFixture, o_id1);
wheel1 = physics_joint_wheel_create(id, o_id1, o_id1.x, o_id1.y, 0, 0.1, true, 10000, 0, 15, 6, false);
physics_fixture_delete(mainFixture);
physics_fixture_delete(wheelFixture);

var mainFixture = physics_fixture_create();
physics_fixture_set_box_shape(mainFixture, 128, 32);
var wheelFixture = physics_fixture_create();
physics_fixture_set_circle_shape(wheelFixture, 32);
var o_id2 = instance_create_layer(x + 320, y + 55, "Instances", oWheel);
physics_fixture_bind(mainFixture, id);
physics_fixture_bind(wheelFixture, o_id2);
wheel2 = physics_joint_wheel_create(id, o_id2, o_id2.x, o_id2.y, 0, 0.1, true, 10000, 0, 15, 6, false);
physics_fixture_delete(mainFixture);
physics_fixture_delete(wheelFixture);